spring.application.name=employee-service


server.port=8081

application.url.scheme= http://
application.url.domain= localhost:
application.url.port= 8080
application.url.path= /department/api/getByCode/



application.properties.message= Fresh Message from Employee-service
