spring.application.name=employee-service
spring.datasource.url=jdbc:mysql://localhost:3306/employee_db
spring.datasource.username=root
#spring.datasource.password=root

spring.jsp.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=*

server.port=8081

application.url.scheme= http://
application.url.domain= localhost:
application.url.port= 8080
application.url.path= /department/api/getByCode/

eureka.server.client.serverUrl.defaultZone= http://localhost:8761/eureka/

application.properties.message= Fresh Message from Employee-service
